const userData = [
    {
        "Block credential": "FALSE",
        "City": "Bellevue",
        "Country/Region": "United States",
        "Department": "Retail",
        "DirSyncEnabled": "",
        "Display name": "Adele Vance",
        "Fax": "",
        "First name": "Adele",
        "Last dirsync time": "",
        "Last name": "Vance",
        "Last password change time stamp": "2021-09-05 23:19:44Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "96ca293c-29dd-4668-a763-ee407bd935d7",
        "Office": "18/2111",
        "Password never expires": "",
        "Phone number": "'+1 425 555 0109",
        "Postal code": 98004,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:AdeleV@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "WA",
        "Street address": "205 108th Ave. NE, Suite 400",
        "Strong password required": "",
        "Title": "Retail Manager",
        "Usage location": "US",
        "User principal name": "AdeleV@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:59:00Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Adele%20Vance.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "San Diego",
        "Country/Region": "United States",
        "Department": "Marketing",
        "DirSyncEnabled": "",
        "Display name": "Alex Wilber",
        "Fax": "",
        "First name": "Alex",
        "Last dirsync time": "",
        "Last name": "Wilber",
        "Last password change time stamp": "2022-01-14 19:04:23Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "8b1d7dd9-48ba-4358-a9b3-1b08daa2d68a",
        "Office": "131/1104",
        "Password never expires": "",
        "Phone number": "'+1 858 555 0110",
        "Postal code": 92121,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:AlexW@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "CA",
        "Street address": "9256 Towne Center Dr., Suite 400",
        "Strong password required": "",
        "Title": "Marketing Assistant",
        "Usage location": "US",
        "User principal name": "AlexW@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:59:01Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Alex%20Wilber.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "Birmingham",
        "Country/Region": "United States",
        "Department": "HR",
        "DirSyncEnabled": "",
        "Display name": "Diego Siciliani",
        "Fax": "",
        "First name": "Diego",
        "Last dirsync time": "",
        "Last name": "Siciliani",
        "Last password change time stamp": "2022-02-11 17:55:36Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "8ec6a7f8-856e-4e19-be92-0845bf4ebc42",
        "Office": "14/1108",
        "Password never expires": "",
        "Phone number": "'+1 205 555 0108",
        "Postal code": 35243,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:DiegoS@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "AL",
        "Street address": "3535 Gradview Parkway Suite 335",
        "Strong password required": "",
        "Title": "HR Manager",
        "Usage location": "US",
        "User principal name": "DiegoS@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:59:02Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Diego%20Siciliani.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "Bloomington",
        "Country/Region": "United States",
        "Department": "R&D",
        "DirSyncEnabled": "",
        "Display name": "Grady Archie",
        "Fax": "",
        "First name": "Grady",
        "Last dirsync time": "",
        "Last name": "Archie",
        "Last password change time stamp": "2022-03-14 14:45:23Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "302ddc87-c65a-437f-83de-aa8672f8e8a3",
        "Office": "19/2109",
        "Password never expires": "",
        "Phone number": "'+1 309 555 0104",
        "Postal code": 61704,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:GradyA@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "IL",
        "Street address": "2203 E. Empire St., Suite J",
        "Strong password required": "",
        "Title": "Designer",
        "Usage location": "US",
        "User principal name": "GradyA@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:59:03Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Grady%20Archie.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "Fort Lauderdale",
        "Country/Region": "United States",
        "Department": "R&D",
        "DirSyncEnabled": "",
        "Display name": "Henrietta Mueller",
        "Fax": "",
        "First name": "Henrietta",
        "Last dirsync time": "",
        "Last name": "Mueller",
        "Last password change time stamp": "2022-07-12 15:30:05Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "73756995-6792-4bd3-b9c0-0307d0b3f8b3",
        "Office": "18/1106",
        "Password never expires": "",
        "Phone number": "'+1 954 555 0118",
        "Postal code": 33309,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:HenriettaM@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "FL",
        "Street address": "6750 North Andrews Ave., Suite 400",
        "Strong password required": "",
        "Title": "Developer",
        "Usage location": "US",
        "User principal name": "HenriettaM@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:59:04Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Henrietta%20Mueller.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "Tulsa",
        "Country/Region": "United States",
        "Department": "Sales",
        "DirSyncEnabled": "",
        "Display name": "Isaiah Langer",
        "Fax": "",
        "First name": "Isaiah",
        "Last dirsync time": "",
        "Last name": "Langer",
        "Last password change time stamp": "2022-07-12 15:34:24Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "b566f96d-839e-460e-936a-0597ae56f725",
        "Office": "20/1101",
        "Password never expires": "",
        "Phone number": "'+1 918 555 0101",
        "Postal code": 74133,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:IsaiahL@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "OK",
        "Street address": "7633 E. 63rd Place, Suite 300",
        "Strong password required": "",
        "Title": "Sales Rep",
        "Usage location": "US",
        "User principal name": "IsaiahL@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:59:05Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Isaiah%20Langer.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "Louisville",
        "Country/Region": "United States",
        "Department": "Engineering",
        "DirSyncEnabled": "",
        "Display name": "Johanna Lorenz",
        "Fax": "",
        "First name": "Johanna",
        "Last dirsync time": "",
        "Last name": "Lorenz",
        "Last password change time stamp": "2020-05-23 19:59:06Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "2d8dcbdf-2142-4e72-98d3-75269f4d3f1a",
        "Office": "23/2102",
        "Password never expires": "",
        "Phone number": "'+1 502 555 0102",
        "Postal code": 40223,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:JohannaL@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "KY",
        "Street address": "9900 Corporate Campus Dr., Suite 3000",
        "Strong password required": "",
        "Title": "Senior Engineer",
        "Usage location": "US",
        "User principal name": "JohannaL@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:59:06Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Johanna%20Lorenz.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "Charlotte",
        "Country/Region": "United States",
        "Department": "Legal",
        "DirSyncEnabled": "",
        "Display name": "Joni Sherman",
        "Fax": "",
        "First name": "Joni",
        "Last dirsync time": "",
        "Last name": "Sherman",
        "Last password change time stamp": "2020-05-23 19:59:07Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "0acb753a-f73f-4c20-9964-ffafe85a3d3d",
        "Office": "20/1109",
        "Password never expires": "",
        "Phone number": "'+1 980 555 0101",
        "Postal code": 28273,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:JoniS@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "NC",
        "Street address": "8055 Microsoft Way",
        "Strong password required": "",
        "Title": "Paralegal",
        "Usage location": "US",
        "User principal name": "JoniS@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:59:08Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Joni%20Sherman.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "",
        "Country/Region": "",
        "Department": "",
        "DirSyncEnabled": "",
        "Display name": "Laura E Fernandez",
        "Fax": "",
        "First name": "Laura",
        "Last dirsync time": "",
        "Last name": "Fernandez",
        "Last password change time stamp": "2022-02-04 00:50:38Z",
        "License assignment details": "",
        "Licenses": "Microsoft Power Automate Free+Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "13238863-74bb-4f00-9a51-9880939b361f",
        "Office": "",
        "Password never expires": "FALSE",
        "Phone number": "",
        "Postal code": "",
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:LauraFernandez@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "",
        "Street address": "",
        "Strong password required": "TRUE",
        "Title": "Staff/Assistant",
        "Usage location": "AR",
        "User principal name": "LauraFernandez@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-25 19:46:28Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Laura%20E Fernandez.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "Overland Park",
        "Country/Region": "United States",
        "Department": "Manufacturing",
        "DirSyncEnabled": "",
        "Display name": "Lee Gu",
        "Fax": "",
        "First name": "Lee",
        "Last dirsync time": "",
        "Last name": "Gu",
        "Last password change time stamp": "2020-05-23 19:58:56Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "8d3913f6-9bf3-41ae-b2bc-f0a4d97c2c79",
        "Office": "23/3101",
        "Password never expires": "",
        "Phone number": "'+1 913 555 0101",
        "Postal code": 66210,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:LeeG@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "KS",
        "Street address": "10801 Mastin Blvd., Suite 620",
        "Strong password required": "",
        "Title": "Director",
        "Usage location": "US",
        "User principal name": "LeeG@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:58:57Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Lee%20Gu.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "Tulsa",
        "Country/Region": "United States",
        "Department": "Engineering",
        "DirSyncEnabled": "",
        "Display name": "Lidia Holloway",
        "Fax": "",
        "First name": "Lidia",
        "Last dirsync time": "",
        "Last name": "Holloway",
        "Last password change time stamp": "2020-05-23 19:59:08Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "f8104839-2023-446e-a137-475f9e52821f",
        "Office": "20/2107",
        "Password never expires": "",
        "Phone number": "'+1 918 555 0107",
        "Postal code": 74133,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:LidiaH@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "OK",
        "Street address": "7633 E. 63rd Place, Suite 300",
        "Strong password required": "",
        "Title": "Product Manager",
        "Usage location": "US",
        "User principal name": "LidiaH@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:59:09Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Lidia%20Holloway.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "Tulsa",
        "Country/Region": "United States",
        "Department": "Retail",
        "DirSyncEnabled": "",
        "Display name": "Lynne Robbins",
        "Fax": "",
        "First name": "Lynne",
        "Last dirsync time": "",
        "Last name": "Robbins",
        "Last password change time stamp": "2020-05-23 19:59:10Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "9f484e52-224c-4797-90f2-81a2041d291c",
        "Office": "20/1104",
        "Password never expires": "",
        "Phone number": "'+1 918 555 0104",
        "Postal code": 74133,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:LynneR@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "OK",
        "Street address": "7633 E. 63rd Place, Suite 300",
        "Strong password required": "",
        "Title": "Planner",
        "Usage location": "US",
        "User principal name": "LynneR@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:59:10Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Lynne%20Robbins.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "Pittsburgh",
        "Country/Region": "United States",
        "Department": "Marketing",
        "DirSyncEnabled": "",
        "Display name": "Megan Bowen",
        "Fax": "",
        "First name": "Megan",
        "Last dirsync time": "",
        "Last name": "Bowen",
        "Last password change time stamp": "2020-05-23 19:59:11Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "dc5cbf06-11c4-48aa-bd4d-ac61c2095f8a",
        "Office": "12/1110",
        "Password never expires": "",
        "Phone number": "'+1 412 555 0109",
        "Postal code": 15212,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:MeganB@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "PA",
        "Street address": "30 Isabella St., Second Floor",
        "Strong password required": "",
        "Title": "Marketing Manager",
        "Usage location": "US",
        "User principal name": "MeganB@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:59:11Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Megan%20Bowen.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "San Diego",
        "Country/Region": "United States",
        "Department": "Sales & Marketing",
        "DirSyncEnabled": "",
        "Display name": "Miriam Graham",
        "Fax": "",
        "First name": "Miriam",
        "Last dirsync time": "",
        "Last name": "Graham",
        "Last password change time stamp": "2020-05-23 19:58:58Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "98eb6d36-7a30-45cb-bf2e-d5c94f53526c",
        "Office": "131/2103",
        "Password never expires": "",
        "Phone number": "'+1 858 555 0109",
        "Postal code": 92121,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:MiriamG@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "CA",
        "Street address": "9255 Towne Center Dr., Suite 400",
        "Strong password required": "",
        "Title": "Director",
        "Usage location": "US",
        "User principal name": "MiriamG@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:58:58Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Miriam%20Graham.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "Seattle",
        "Country/Region": "United States",
        "Department": "Operations",
        "DirSyncEnabled": "",
        "Display name": "Nestor Wilke",
        "Fax": "",
        "First name": "Nestor",
        "Last dirsync time": "",
        "Last name": "Wilke",
        "Last password change time stamp": "2020-05-23 19:58:59Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "2c31da93-6384-4606-87ef-9e3d483f827c",
        "Office": "36/2121",
        "Password never expires": "",
        "Phone number": "'+1 206 555 0105",
        "Postal code": 98109,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:NestorW@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "WA",
        "Street address": "320 Westlake Ave N. Thomas St.",
        "Strong password required": "",
        "Title": "Director",
        "Usage location": "US",
        "User principal name": "NestorW@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:58:59Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Nestor%20Wilke.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "Buenos Aires",
        "Country/Region": "Argentina",
        "Department": "Buenos Aires",
        "DirSyncEnabled": "",
        "Display name": "Pablo Fernandez",
        "Fax": "",
        "First name": "Pablo",
        "Last dirsync time": "",
        "Last name": "Fernandez",
        "Last password change time stamp": "2021-08-31 01:49:12Z",
        "License assignment details": "",
        "Licenses": "Microsoft Power Automate Free+Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "0c88c4d9-80b8-4f23-a36c-4068b1790d1b",
        "Office": "",
        "Password never expires": "",
        "Phone number": 4251001000,
        "Postal code": 19030341,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:pablof@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "Buenos Aires",
        "Street address": "",
        "Strong password required": "",
        "Title": "CTO",
        "Usage location": "US",
        "User principal name": "pablof@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:53:49Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Pablo%20Fernandez.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "Louisville",
        "Country/Region": "United States",
        "Department": "Executive Management",
        "DirSyncEnabled": "",
        "Display name": "Patti Fernandez",
        "Fax": "",
        "First name": "Patti",
        "Last dirsync time": "",
        "Last name": "Fernandez",
        "Last password change time stamp": "2020-05-23 19:58:56Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "53b08bf7-da59-4d77-a786-b438288fefe3",
        "Office": "15/1102",
        "Password never expires": "",
        "Phone number": "'+1 502 555 0144",
        "Postal code": 40223,
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:PattiF@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "KY",
        "Street address": "9900 Corporate Campus Dr., Suite 3000",
        "Strong password required": "",
        "Title": "President",
        "Usage location": "US",
        "User principal name": "PattiF@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:58:56Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Patti%20Fernandez.jpg"
    },
    {
        "Block credential": "FALSE",
        "City": "Cairo",
        "Country/Region": "Egypt",
        "Department": "Finance",
        "DirSyncEnabled": "",
        "Display name": "Pradeep Gupta",
        "Fax": "",
        "First name": "Pradeep",
        "Last dirsync time": "",
        "Last name": "Gupta",
        "Last password change time stamp": "2021-10-01 17:07:18Z",
        "License assignment details": "",
        "Licenses": "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)",
        "Mobile Phone": "",
        "Oath token meta data": "",
        "Object Id": "bc8970be-e57b-4476-b7bb-35d52ea6b831",
        "Office": "98/2202",
        "Password never expires": "",
        "Phone number": "'+20 255501070",
        "Postal code": "",
        "Preferred data location": "",
        "Preferred language": "en-US",
        "Proxy addresses": "SMTP:PradeepG@tecnosharedev.onmicrosoft.com",
        "Release track": "",
        "Soft deletion time stamp": "",
        "State": "",
        "Street address": "Smart Village, Kilo 28, Cairo/Alex Desert Road",
        "Strong password required": "",
        "Title": "Accountant",
        "Usage location": "US",
        "User principal name": "PradeepG@tecnosharedev.onmicrosoft.com",
        "When created": "2020-05-23 19:59:12Z",
        "Picture": "https://raw.githubusercontent.com/ORT-PabloFernandez/PNTP2-REACT-EJEMPLO/main/public/img/Pradeep%20Gupta.jpg"
    }
]

export default userData;